version: '3'
services:
  yang-explorer:
    image: hellt/yangexplorer-docker
    volumes:
      - yangdata:/yang-explorer/server/data
    ports:
      - "8088:8088"
  influxdb:
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:6.4.3
    ports: 
      - 3000:3000
  telegraf:
    build: telemetry/telegraf
    ports:
      - "57500:57500"
    volumes:
      - ./telemetry/telegraf/data/telegraf.conf:/etc/telegraf/telegraf.conf
  development:
    build: python/development
    volumes:
      - ./python/development/data:/app
volumes:
  yangdata:
  influxdb:
