version: '3'
services:
  influxdb:
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:6.4.3
    ports: 
      - 3000:3000
  telegraf:
    build: telegraf
    ports:
      - "57500:57500"
    volumes:
      - ./telegraf/data/telegraf.conf:/etc/telegraf/telegraf.conf
volumes:
  influxdb:
